'use strict'

// Lo que se publica no lleva firmas de IA, salvo que el proyecto lo declare (caso 300).

const { tempRoot } = require('../support/environment')
const { blocked, git, initRepo, chatSession } = require('../support/hooks-harness')

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execute } = require('../../engine/hooks/run')
const { signatureIn, ordersSignature } = require('../../engine/hooks/ai-signature')

const SIGNED = /termina con .*\. Lo que se publica no lleva firmas de IA \(R8\)/

// Un repositorio de la sesión con un commit. La sesión se fija por entorno, que es como la conoce un guard.
function inRepo(prefix, body) {
  const root = tempRoot(prefix)
  initRepo(root)
  fs.writeFileSync(path.join(root, 'a.txt'), 'uno\n')
  git(['add', 'a.txt'], root)
  git(['commit', '-qm', 'uno'], root)
  const saved = { dir: process.env.CLAUDE_PROJECT_DIR, ops: process.env.OPS_ROOT }
  process.env.CLAUDE_PROJECT_DIR = root
  delete process.env.OPS_ROOT
  try { return body(root, (command) => ({ cwd: root, tool_input: { command } })) } finally {
    for (const [name, key] of [['CLAUDE_PROJECT_DIR', 'dir'], ['OPS_ROOT', 'ops']]) {
      if (saved[key] === undefined) delete process.env[name]
      else process.env[name] = saved[key]
    }
  }
}
const message = (...lines) => `git commit -m "$(cat <<'EOF'\n${lines.join('\n')}\nEOF\n)"`

test('un commit firmado por un asistente se frena, y uno sin firma o con un coautor humano no', () => {
  inRepo('ops-hook-firma-', (root, at) => {
    const signed = [
      'Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>',
      'co-authored-by: GitHub Copilot <copilot@github.com>',
      '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      'Generated by Codex',
      'Assisted-by: Claude:opus',
      'Claude-Session: https://claude.ai/code/session_x',
    ]
    for (const line of signed) blocked('ai-signature', at(message('fix: x', '', line)), SIGNED)
    // Por dónde llegue el mensaje: un segundo `-m`, que git pega como último párrafo; un archivo; y los otros
    // dos comandos cuyo `-m` queda en la historia.
    const trailer = 'Co-Authored-By: Claude <noreply@anthropic.com>'
    blocked('ai-signature', at(`git -C ${root} commit -m "fix: x" -m "${trailer}"`), SIGNED)
    fs.writeFileSync(path.join(root, 'MENSAJE'), `fix: x\n\n${trailer}\n`)
    blocked('ai-signature', at('git commit -F MENSAJE'), SIGNED)
    blocked('ai-signature', at(`git merge --no-ff rama -m "merge" -m "${trailer}"`), /comando de git/)
    blocked('ai-signature', at(`git tag -a v1 -m "v1" -m "${trailer}"`), /comando de git/)

    // El otro lado, que es el que importa para no frenar de más: lo que no es una firma pasa.
    const clean = [
      message('fix: x'),
      message('fix: x', '', 'Co-authored-by: Ana Pérez <ana@example.test>'),
      message('fix: x', '', 'Reviewed-by: Claudia Gómez <c@example.test>'),
      // Un nombre de persona no es un asistente por parecerse a uno, ni por trabajar donde se hace uno.
      message('fix: x', '', 'Co-Authored-By: Claude Dupont <claude.dupont@example.test>'),
      message('fix: x', '', 'Co-authored-by: Devin Smith <devin@example.test>'),
      message('fix: x', '', 'Co-authored-by: Sam Lee <sam@openai.com>'),
      message('fix: x', '', 'Co-authored-by: Ana <ana@example.test> (pair with copilot)'),
      message('feat: paginate', '', 'Generated by cursor-based pagination helper'),
      // La firma citada en un cuerpo que sigue hablando después no cierra el mensaje, empiece donde empiece.
      message('fix: strip the trailer', '', 'A run added', trailer, 'to every planning commit, so it is removed.'),
      // Y lo que se juzga es el mensaje: un archivo escrito en el mismo comando no lo es.
      `cat > notas.md <<'EOF'\n${trailer}\nEOF\ngit commit -m "docs: add notes"`,
      message('fix: x', '', 'Assisted-by: Ana Pérez'),
      'git commit -F NO-EXISTE',
      // `-n`, `-b` y `-t` son texto sólo en `gh`: en otro comando de la misma línea son otra cosa.
      `git commit -m "fix: x" && grep -n "${trailer}" notas.md`,
      // Hablar de la firma en la prosa del cuerpo no es firmar: sólo cuenta como línea propia.
      message('fix: strip the trailer', '', 'A run added "Co-Authored-By: Claude" and',
        'a "Generated with Claude Code" footer.'),
      'git status && git log -1',
    ]
    for (const command of clean) assert.doesNotThrow(() => execute('ai-signature', at(command)), command)
  })
})

test('el texto de un pull request se mira igual, y un gh que no publica no', () => {
  inRepo('ops-hook-firma-pr-', (_root, at) => {
    const footer = '🤖 Generated with [Claude Code](https://claude.com/claude-code)'
    const verbs = ['pr create --title x --body', 'pr comment 12 --body', 'pr edit 12 --body', 'issue comment 3 --body']
    for (const verb of verbs) {
      blocked('ai-signature', at(`gh ${verb} "$(cat <<'EOF'\nResumen\n\n${footer}\nEOF\n)"`), /el texto de este 'gh'/)
      assert.doesNotThrow(() => execute('ai-signature', at(`gh ${verb} "Resumen sin firma"`)), verb)
    }
    assert.doesNotThrow(() => execute('ai-signature', at(`gh pr view 12 --json body -q '${footer}'`)), 'sólo lee')
    // El pie que deja la herramienta trae el enlace a la sesión en un párrafo aparte: sigue siendo el cierre.
    const linked = `Resumen\n\n${footer}\n\nhttps://claude.ai/code/session_x`
    blocked('ai-signature', at(`gh pr create --title x --body "$(cat <<'EOF'\n${linked}\nEOF\n)"`), /de este 'gh'/)
    blocked('ai-signature', at(`gh release create v1 --notes "$(cat <<'EOF'\nNotas\n\n${footer}\nEOF\n)"`), /'gh'/)
    fs.writeFileSync(path.join(_root, 'CUERPO.md'), `Resumen\n\n${footer}\n`)
    blocked('ai-signature', at('gh pr create --title x --body-file CUERPO.md'), /el texto de este 'gh'/)
  })
})

test('el proyecto que quiere la firma lo declara, y un repositorio ajeno no se juzga', () => {
  inRepo('ops-hook-firma-switch-', (root, at) => {
    const signed = message('fix: x', '', 'Co-Authored-By: Claude <noreply@anthropic.com>')
    blocked('ai-signature', at(signed), SIGNED)
    fs.mkdirSync(path.join(root, 'planning'))
    const config = (runner) => fs.writeFileSync(path.join(root, 'ops.config.json'),
      JSON.stringify({ project: 'x', mode: 'embedded', workspaceRoots: [{ name: 'main', path: '.' }], runner }))
    config({ allowAiSignature: false })
    blocked('ai-signature', at(signed), /runner\.allowAiSignature: true/)
    config({ allowAiSignature: true })
    assert.doesNotThrow(() => execute('ai-signature', at(signed)), 'el proyecto lo declaró')
    config({})

    const foreign = fs.mkdtempSync(path.join(os.tmpdir(), 'ops-hook-firma-ajeno-'))
    initRepo(foreign)
    const elsewhere = signed.replace('git commit', `git -C ${foreign} commit`)
    assert.doesNotThrow(() => execute('ai-signature', at(elsewhere)), 'ajeno')
  })
})

test('la firma se ve por cualquier vía por la que llegue el comando', () => {
  inRepo('ops-hook-firma-vias-', (root) => {
    const command = message('fix: x', '', 'Co-Authored-By: Claude <noreply@anthropic.com>')
    blocked('ai-signature', { cwd: root, tool_input: { cmd: command } }, SIGNED)
    blocked('ai-signature', { cwd: root, command }, SIGNED)
    blocked('ai-signature', { cwd: root, input: { command } }, SIGNED)
    const merge = `gh pr merge 12 --squash --body ${command.slice(14)}`
    blocked('ai-signature', { cwd: root, tool_input: { command: merge } }, /el texto de este 'gh'/)
  })
})

test('lo que la persona pide en el chat nombrando la firma no se frena', () => {
  inRepo('ops-hook-firma-chat-', (root) => {
    const command = message('fix: x', '', 'Co-Authored-By: Claude <noreply@anthropic.com>')
    const chat = chatSession()
    const call = (extend) => extend({ cwd: root, tool_input: { command } })
    try {
      blocked('ai-signature', call(chat.says('commiteá lo que hay')), SIGNED)
      blocked('ai-signature', call(chat.says('commiteá sin el Co-Authored-By')), SIGNED)
      blocked('ai-signature', call(chat.says('¿le dejo el Co-Authored-By?')), SIGNED)
      const asked = chat.says('commiteá y dejale el Co-Authored-By de Claude')
      assert.doesNotThrow(() => execute('ai-signature', call(asked)))
    } finally { chat.close() }
  })
  assert.equal(ordersSignature('Dejá el Generated with en el cuerpo del PR'), true)
  assert.equal(ordersSignature('No pongas Generated with. Commiteá'), false)
  assert.equal(ordersSignature('commiteá'), false)
})

test('qué cuenta como firma', () => {
  assert.equal(signatureIn('Co-Authored-By: Gemini CLI <g@example.test>'), 'un Co-Authored-By de un asistente')
  assert.equal(signatureIn('  Generated with Cursor'), '«Generated with» de un asistente')
  assert.equal(signatureIn('fix: generated with care by a person'), '')
  assert.equal(signatureIn('Co-Authored-By: Claude <noreply@anthropic.com>\nSigned-off-by: Ana <a@example.test>'),
    'un Co-Authored-By de un asistente', 'otro trailer después no la vuelve prosa')
  assert.equal(signatureIn('Co-Authored-By: Claude <noreply@anthropic.com>\nand that is why it fails.'), '')
  assert.equal(signatureIn('Co-Authored-By: Geminiano Ruiz <g@example.test>'), '', 'una persona no es un asistente')
})
