'use strict'

// Lo que se publica no lleva firmas de IA, salvo que el proyecto lo declare (caso 300).

const { tempRoot } = require('../support/environment')
const { blocked, git, initRepo } = require('../support/hooks-harness')

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execute } = require('../../engine/hooks/run')
const { signatureIn } = require('../../engine/hooks/ai-signature')

const SIGNED = /trae .*\. Lo que se publica no lleva firmas de IA \(R8\)/

// Un repositorio de la sesión con un commit. La sesión se fija por entorno, que es como la conoce un guard.
function inRepo(prefix, body) {
  const root = tempRoot(prefix)
  initRepo(root)
  fs.writeFileSync(path.join(root, 'a.txt'), 'uno\n')
  git(['add', 'a.txt'], root)
  git(['commit', '-qm', 'uno'], root)
  const saved = { dir: process.env.CLAUDE_PROJECT_DIR, ops: process.env.OPS_ROOT }
  process.env.CLAUDE_PROJECT_DIR = root
  delete process.env.OPS_ROOT
  try { return body(root, (command) => ({ cwd: root, tool_input: { command } })) } finally {
    for (const [name, key] of [['CLAUDE_PROJECT_DIR', 'dir'], ['OPS_ROOT', 'ops']]) {
      if (saved[key] === undefined) delete process.env[name]
      else process.env[name] = saved[key]
    }
  }
}
const message = (...lines) => `git commit -m "$(cat <<'EOF'\n${lines.join('\n')}\nEOF\n)"`

test('un commit firmado por un asistente se frena, y uno sin firma o con un coautor humano no', () => {
  inRepo('ops-hook-firma-', (root, at) => {
    const signed = [
      'Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>',
      'co-authored-by: GitHub Copilot <copilot@github.com>',
      '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      'Generated by Codex',
      'Assisted-by: un-modelo',
      'Claude-Session: https://claude.ai/code/session_x',
    ]
    for (const line of signed) blocked('ai-signature', at(message('fix: x', '', line)), SIGNED)
    // El límite declarado, fijado para que se note si alguien lo mueve: una firma que no empieza su línea
    // —pasada como un segundo `-m` suelto— no se ve. Verla pediría leer también la que va citada en la prosa
    // de un cuerpo, que es frenar a quien explica el problema.
    assert.doesNotThrow(() => execute('ai-signature',
      at(`git -C ${root} commit -m "fix: x" -m "Co-Authored-By: Claude <noreply@anthropic.com>"`)))

    // El otro lado, que es el que importa para no frenar de más: lo que no es una firma pasa.
    const clean = [
      message('fix: x'),
      message('fix: x', '', 'Co-authored-by: Ana Pérez <ana@example.test>'),
      message('fix: x', '', 'Reviewed-by: Claudia Gómez <c@example.test>'),
      // Un nombre de persona no es un asistente por parecerse a uno, ni por trabajar donde se hace uno.
      message('fix: x', '', 'Co-Authored-By: Claude Dupont <claude.dupont@example.test>'),
      message('fix: x', '', 'Co-authored-by: Devin Smith <devin@example.test>'),
      message('fix: x', '', 'Co-authored-by: Sam Lee <sam@openai.com>'),
      message('fix: x', '', 'Co-authored-by: Ana <ana@example.test> (pair with copilot)'),
      message('feat: paginate', '', 'Generated by cursor-based pagination helper'),
      // Hablar de la firma en la prosa del cuerpo no es firmar: sólo cuenta como línea propia.
      message('fix: strip the trailer', '', 'A run added "Co-Authored-By: Claude" and',
        'a "Generated with Claude Code" footer.'),
      'git status && git log -1',
    ]
    for (const command of clean) assert.doesNotThrow(() => execute('ai-signature', at(command)), command)
  })
})

test('el texto de un pull request se mira igual, y un gh que no publica no', () => {
  inRepo('ops-hook-firma-pr-', (_root, at) => {
    const footer = '🤖 Generated with [Claude Code](https://claude.com/claude-code)'
    const verbs = ['pr create --title x --body', 'pr comment 12 --body', 'pr edit 12 --body', 'issue comment 3 --body']
    for (const verb of verbs) {
      blocked('ai-signature', at(`gh ${verb} "$(cat <<'EOF'\nResumen\n\n${footer}\nEOF\n)"`), /el texto de este 'gh'/)
      assert.doesNotThrow(() => execute('ai-signature', at(`gh ${verb} "Resumen sin firma"`)), verb)
    }
    assert.doesNotThrow(() => execute('ai-signature', at(`gh pr view 12 --json body -q '${footer}'`)), 'sólo lee')
  })
})

test('el proyecto que quiere la firma lo declara, y un repositorio ajeno no se juzga', () => {
  inRepo('ops-hook-firma-switch-', (root, at) => {
    const signed = message('fix: x', '', 'Co-Authored-By: Claude <noreply@anthropic.com>')
    blocked('ai-signature', at(signed), SIGNED)
    fs.mkdirSync(path.join(root, 'planning'))
    const config = (runner) => fs.writeFileSync(path.join(root, 'ops.config.json'),
      JSON.stringify({ project: 'x', mode: 'embedded', workspaceRoots: [{ name: 'main', path: '.' }], runner }))
    config({ allowAiSignature: false })
    blocked('ai-signature', at(signed), /runner\.allowAiSignature: true/)
    config({ allowAiSignature: true })
    assert.doesNotThrow(() => execute('ai-signature', at(signed)), 'el proyecto lo declaró')
    config({})

    const foreign = fs.mkdtempSync(path.join(os.tmpdir(), 'ops-hook-firma-ajeno-'))
    initRepo(foreign)
    const elsewhere = signed.replace('git commit', `git -C ${foreign} commit`)
    assert.doesNotThrow(() => execute('ai-signature', at(elsewhere)), 'ajeno')
  })
})

test('la firma se ve por cualquier vía por la que llegue el comando', () => {
  inRepo('ops-hook-firma-vias-', (root) => {
    const command = message('fix: x', '', 'Co-Authored-By: Claude <noreply@anthropic.com>')
    blocked('ai-signature', { cwd: root, tool_input: { cmd: command } }, SIGNED)
    blocked('ai-signature', { cwd: root, command }, SIGNED)
    blocked('ai-signature', { cwd: root, input: { command } }, SIGNED)
    const merge = `gh pr merge 12 --squash --body ${command.slice(14)}`
    blocked('ai-signature', { cwd: root, tool_input: { command: merge } }, /el texto de este 'gh'/)
  })
})

test('qué cuenta como firma', () => {
  assert.equal(signatureIn('Co-Authored-By: Gemini CLI <g@example.test>'), 'un Co-Authored-By de un asistente')
  assert.equal(signatureIn('  Generated with Cursor'), '«Generated with» de un asistente')
  assert.equal(signatureIn('fix: generated with care by a person'), '')
  assert.equal(signatureIn('Co-Authored-By: Geminiano Ruiz <g@example.test>'), '', 'una persona no es un asistente')
})
